apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: data-aggregator
        image: ghcr.io/giacomosirri/data-aggregator:latest
        env:
          - name: SCW_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SCW_ACCESS_KEY
          - name: SCW_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SCW_SECRET_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ghcr-login-secret