apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-consumer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: data-consumer
        image: ghcr.io/giacomosirri/data-consumer:latest
        env:
          - name: SCW_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SCW_ACCESS_KEY
          - name: SCW_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: SCW_SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ghcr-login