apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: data-aggregator
        image: ghcr.io/giacomosirri/data-aggregator:latest
        env:
        - name: SCW_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: scaleway-credentials
              key: SCW_ACCESS_KEY
        - name: SCW_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scaleway-credentials
              key: SCW_SECRET_KEY
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ghcr-login