apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: data-aggregator
          image: ghcr.io/giacomosirri/data-aggregator:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
