apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema
data:
  schema.sql: |
    CREATE SCHEMA IF NOT EXISTS vehicle_data;
    CREATE TABLE IF NOT EXISTS vehicle_data.telemetry (
      id INTEGER PRIMARY KEY,
      brake_temp REAL,
      "timestamp" TIMESTAMP NOT NULL,
      fuel REAL,
      speed REAL
    );