apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema
  namespace: database
data:
  schema.sql: |
    CREATE SCHEMA IF NOT EXISTS vehicle_data;
    CREATE TABLE IF NOT EXISTS vehicle_data.telemetry (
      "timestamp" TIMESTAMPTZ,
      vehicle_id INTEGER,
      location_x REAL,
      location_y REAL,
      brake_temp REAL,
      fuel REAL,
      speed REAL,
      PRIMARY KEY ("timestamp", vehicle_id)
    );