apiVersion: batch/v1
kind: Job
metadata:
  name: init-schema
spec:
  template:
    spec:
      containers:
      - name: psql-init
        image: postgres:15
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: DB_CONNECTION_STRING
        command: ["sh", "-c"]
        args:
          - psql "$DB_CONNECTION_STRING" -f /sql/schema.sql
        volumeMounts:
        - name: sql
          mountPath: /sql
      volumes:
      - name: sql
        configMap:
          name: db-schema
      restartPolicy: Never
  backoffLimit: 1
