apiVersion: batch/v1
kind: Job
metadata:
  name: init-schema
spec:
  template:
    spec:
      containers:
      - name: psql-init
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        command: ["sh", "-c"]
        args:
          - psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -f /sql/schema.sql
        volumeMounts:
        - name: sql
          mountPath: /sql
      volumes:
      - name: sql
        configMap:
          name: db-schema
      restartPolicy: Never
  backoffLimit: 1
