apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  postgre-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: grafana-postgresql-datasource
        type: postgres
        url: ${DB_CONNECTION_STRING}
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          postgresVersion: 1500
          sslmode: 'disable'
          timescaledb: false