apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  postgre-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: grafana-postgresql-datasource
        type: postgres
        url: ${POSTGRES_HOST}:${POSTGRES_PORT}
        access: proxy
        user: ${POSTGRES_USER}
        isDefault: true
        editable: true
        secureJsonData:
          password: ${POSTGRES_PASSWORD}
        jsonData:
          database: ${POSTGRES_DB}
          postgresVersion: 1600
          sslmode: 'disable'
          timescaledb: false