name: Create and publish Docker images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CONSUMER: data-consumer
  IMAGE_NAME_AGGREGATOR: data-aggregator

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta for aggregator
        id: meta-aggregator
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AGGREGATOR }}

      - name: Build and push Docker image of aggregator
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          file: app/src/subscribers/Dockerfile-aggregator
          tags: ${{ steps.meta-aggregator.outputs.tags }}
          labels: ${{ steps.meta-aggregator.outputs.labels }}

      - name: Docker meta for consumer
        id: meta-consumer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CONSUMER }}

      - name: Build and push Docker image of consumer
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          file: app/src/subscribers/Dockerfile-consumer
          tags: ${{ steps.meta-consumer.outputs.tags }}
          labels: ${{ steps.meta-consumer.outputs.labels }}