name: Create and publish Docker images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    
env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - name: data-consumer
            dockerfile: Dockerfile-subscriber
          - name: data-aggregator
            dockerfile: Dockerfile-aggregator

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image tag and label
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: app/src/subscribers
          push: true
          file: ${{ matrix.image.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
