name: Destroy resources

on: 
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * 1-5

jobs:
  destroy-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: Set env vars
        run: |
          echo "SCW_ACCESS_KEY=${{ secrets.SCW_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "SCW_SECRET_KEY=${{ secrets.SCW_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.SCW_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SCW_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init -upgrade
        working-directory: terraform

      - name: Run terraform destroy
        run: terraform destroy -auto-approve
        working-directory: terraform