name: Main workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: Set env vars
        run: |
          echo "export SCW_ACCESS_KEY=${{ secrets.SCW_ACCESS_KEY }} \
          export SCW_SECRET_KEY=${{ secrets.SCW_SECRET_KEY }} \
          export AWS_ACCESS_KEY_ID=$SCW_ACCESS_KEY \
          export AWS_SECRET_ACCESS_KEY=$SCW_SECRET_KEY" >> "$GITHUB_OUTPUT"
      
      - run: env

      - name: Initialize Terraform
        run: |
          export SCW_ACCESS_KEY=${{ secrets.SCW_ACCESS_KEY }} \
          export SCW_SECRET_KEY=${{ secrets.SCW_SECRET_KEY }} \
          export AWS_ACCESS_KEY_ID=$SCW_ACCESS_KEY \
          export AWS_SECRET_ACCESS_KEY=$SCW_SECRET_KEY
          cd terraform
          terraform init

      - name: Run terraform plan
        run: terraform plan -var project_name=test
        